In [2]:
import pandas as pd
import json

# Open and read the JSON file line by line
with open('clickbait_with_transcripts.json', 'r') as file:
    lines = file.readlines()

# Try loading the lines to see if it works
try:
    # Try to load the JSON data
    data = [json.loads(line.strip()) for line in lines]
    # Convert the list of JSON objects into a dataframe
    df1 = pd.json_normalize(data)
    
except json.JSONDecodeError as e:
    print(f"Error reading JSON: {e}")

df1 = df1.drop("video_dislikes", axis=1)
df1.head()

channel_id      channel_name  channel_subscribers  \
0  UC7t6FZ5U17ruEXRH1WRxcTQ          Top List                    0   
1  UCa2fBMGQn5Q8hiZ4MX93Tmg     Top 10 Things               424187   
2  UCQ-hpFPF4nOKoKPEAZM_THw           TopTenz              1113188   
3  UCBINYCmwE29fBXCpUI8DgTA  MostAmazingTop10              4129592   
4  UCX--mGSg0UwDjl7MDL8H5Jg         BabbleTop               119764   

   channel_videos  channel_views  video_comments     video_id  video_likes  \
0             193      143713154           131.0  hDcWfBq5bxM       1424.0   
1             345       81296257            62.0  BtHDTsAA3uI        273.0   
2            1437      306666947          1158.0  pqe4AHTpzPg       3607.0   
3            2065     1243277026          2835.0  nEGTPVWnwyo       7638.0   
4             248       53525150           549.0  T9O6rfENh7I       1145.0   

                                         video_title  video_views  \
0  10 Amazing Places That Disappear During High Tide     360859.0   
1              10 Riddles That Will Trick Your Brain      23835.0   
2     Top 10 Worst Moments in DC Comics — TopTenzNet     514051.0   
3       Top 10 Scary American Urban Legends - Part 3     334602.0   
4     Top 10 Things Subway DOESN'T Want You To KNOW!     129069.0   

                                          transcript  
0  10 amazing places that disappear during high t...  
1  feel like you have more common sense than othe...  
2  Top 10 Worst Moments in DC Comics 10. Superman...  
3  Starting off at  number 10 we have The Skunk A...  
4  About ten years ago there was no better bet\nt...

In [3]:
import pandas as pd
import json

# Open and read the JSON file line by line
with open('clickbait_extra_transcripts.json', 'r') as file:
    lines = file.readlines()

# Try loading the lines to see if it works
try:
    # Try to load the JSON data
    data = [json.loads(line.strip()) for line in lines]
    # Convert the list of JSON objects into a dataframe
    df2 = pd.json_normalize(data)
    
except json.JSONDecodeError as e:
    print(f"Error reading JSON: {e}")
df2 = df2.drop(["Video Title", "Views", "Likes", "Dislikes", "Favorites", "video_dislikes"], axis=1)
df2.head()

video_id                                         transcript  \
0  hxwpkM5w3Cc  - I tied up an FBI agent.\n(words pop) If he s...   
1  81mXAkFEkMs  hey what's happening y'all welcome back to ano...   
2  9NQQKNAwaPk  I used to taste your daddy who doesn't love a ...   
3  Y_PQrPRolvM  Hi!\nWho said that giants are imaginary and on...   
4  ZZtYAOpHVYk  [Music] hey guys what's up it's charlie here a...   

                 channel_id  channel_name channel_subscribers  channel_videos  \
0  UCX6OQ3DkcsbYNE6H8uQQuVA       MrBeast           377000000              24   
1  UCwNEx3HyQ_wiCL9LNn3mTSw  Real Bizarre              654000              24   
2  UCmvqviNx70U0l4ZcvUAXxhA    Top 5 Best             5480000              24   
3  UCwNEx3HyQ_wiCL9LNn3mTSw  Real Bizarre              654000              24   
4  UCRyIP2oznv4UPAl1jmKS5kA       Top 10s             5130000              24   

  channel_views video_comments video_likes video_views  \
0   76059412657          94218     4751551   240148567   
1     206980120            917       15166     6905437   
2     836448242           2458       56901     2776197   
3     206980120            660        9680     1294977   
4    1641526994           3677       63330     9247828   

                                   video_title  
0                      I Got Hunted By The FBI  
1  10 Real Life Giants You Won’t Believe Exist  
2  10 Mythical CREATURES That Actually Existed  
3                Real Giants Caught On Camera!  
4                          10 Real Life Giants

In [17]:
clickbait_df = pd.concat([df1, df2], axis=0)


clickbait_df["label"] = pd.Series([1]*len(clickbait_df))
clickbait_df = clickbait_df.dropna()
clickbait_df.isnull().sum()

channel_id             0
channel_name           0
channel_subscribers    0
channel_videos         0
channel_views          0
video_comments         0
video_id               0
video_likes            0
video_title            0
video_views            0
transcript             0
label                  0
dtype: int64

In [18]:
import pandas as pd
import json

# Open and read the JSON file line by line
with open('nonclickbait_with_transcripts.json', 'r') as file:
    lines = file.readlines()

# Try loading the lines to see if it works
try:
    # Try to load the JSON data
    data = [json.loads(line.strip()) for line in lines]
    # Convert the list of JSON objects into a dataframe
    nonclickbait_full_df = pd.json_normalize(data)
    
except json.JSONDecodeError as e:
    print(f"Error reading JSON: {e}")

nonclickbait_full_df = nonclickbait_full_df.drop("video_dislikes", axis=1)
nonclickbait_full_df["label"] = pd.Series([0]*len(nonclickbait_full_df))



nonclickbait_balanced_df = nonclickbait_full_df.sample(n=len(clickbait_df), random_state=42)
nonclickbait_balanced_df["transcript"].isna().sum()


np.int64(0)

In [19]:
yt_videos = pd.concat([clickbait_df, nonclickbait_balanced_df], axis=0).reset_index()
yt_videos = yt_videos.drop("index", axis=1)
yt_videos['transcript'][0]

"10 amazing places that disappear during high tide number 10 a road in France if you're planning a trip to France make sure to be careful which roads you take they might just disappear connecting the Gulf of berf with the island of no pasage dooy is a road that is not only unique but extremely dangerous twice every day when the High Tide Rises the 2.58 M long passage disappears 13 15 ft underwater people use the road two times a day for a few hours special panels on both sides show when it's safe to travel people still get caught between the tides and there are elevated rescue towers for people to climb just in case number nine shivling Stam hesar Mahadev Temple is located in kavi kbo Gujarat India it shieling is located so close to the sea that one can only worship there during low tide the shrine is more than 150 years old and is situated near the Gulf of cambay during high tide the 4-ft Shing is completely submerged but as low tide begins we see the shivling reappear number eight M 

In [25]:
yt_videos_unbalanced = pd.concat([clickbait_df, nonclickbait_full_df], axis=0).reset_index()

# Transcript Only test with MLP and balanced dataset

### data preprocessing and feature extraction

### tfidf embedding

In [21]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer


# Define a function to clean the transcript text
def clean_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove punctuation and any non-alphabetic characters
    text = re.sub(r'[^a-z\s]', '', text)
    return text

# Apply the cleaning function to the transcript column
yt_videos['clean_transcript'] = yt_videos['transcript'].apply(clean_text)

# Initialize a TF-IDF vectorizer with English stop words removed
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)

# Fit the vectorizer on the clean transcripts and transform the text into feature vectors
X = tfidf_vectorizer.fit_transform(yt_videos['clean_transcript'])
y = yt_videos['label']

print("TF-IDF feature matrix shape:", X.shape)


TF-IDF feature matrix shape: (2502, 5000)


### data splitting and model training and evaluation

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 3: Dataset Splitting
# Stratify ensures that both training and test sets maintain the same class distribution
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

# Step 4: Model Training (Random Forest)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)

# Step 5: Model Evaluation
y_pred = rf_clf.predict(X_test)

# Calculate and print evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy on test set:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Training set size: (1751, 5000)
Test set size: (751, 5000)
Accuracy on test set: 0.9027962716378163

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.91      0.90       376
           1       0.91      0.90      0.90       375

    accuracy                           0.90       751
   macro avg       0.90      0.90      0.90       751
weighted avg       0.90      0.90      0.90       751

Confusion Matrix:
[[342  34]
 [ 39 336]]


In [23]:
from sklearn.neural_network import MLPClassifier

# Step 4: Model Training using MLP
# Configure the MLP with one hidden layer of 100 neurons, using ReLU activation and Adam optimizer
mlp_clf = MLPClassifier(hidden_layer_sizes=(100,), activation='relu', solver='adam', 
                        random_state=42, max_iter=300)

mlp_clf.fit(X_train, y_train)

# Step 5: Model Evaluation
y_pred = mlp_clf.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy on test set:", accuracy)

# Detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy on test set: 0.8801597869507324

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.84      0.88       376
           1       0.85      0.92      0.88       375

    accuracy                           0.88       751
   macro avg       0.88      0.88      0.88       751
weighted avg       0.88      0.88      0.88       751

Confusion Matrix:
[[317  59]
 [ 31 344]]


In [24]:
from sklearn.linear_model import LogisticRegression

# Model Training: Train a logistic regression model
logreg_clf = LogisticRegression(random_state=42, max_iter=1000)
logreg_clf.fit(X_train, y_train)

# Model Evaluation: Predict and evaluate on the test set
y_pred = logreg_clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy on test set:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy on test set: 0.9014647137150466

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.92      0.90       376
           1       0.91      0.89      0.90       375

    accuracy                           0.90       751
   macro avg       0.90      0.90      0.90       751
weighted avg       0.90      0.90      0.90       751

Confusion Matrix:
[[345  31]
 [ 43 332]]


### training with unbalanced dataset

In [26]:


# Apply the cleaning function to the transcript column
yt_videos_unbalanced['clean_transcript'] = yt_videos_unbalanced['transcript'].apply(clean_text)

# Initialize a TF-IDF vectorizer with English stop words removed
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)

# Fit the vectorizer on the clean transcripts and transform the text into feature vectors
X = tfidf_vectorizer.fit_transform(yt_videos_unbalanced['clean_transcript'])
y = yt_videos_unbalanced['label']

print("TF-IDF feature matrix shape:", X.shape)


TF-IDF feature matrix shape: (8763, 5000)


In [27]:
# Step 3: Dataset Splitting
# Stratify ensures that both training and test sets maintain the same class distribution
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

# Step 4: Model Training (Random Forest)
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)

# Step 5: Model Evaluation
y_pred = rf_clf.predict(X_test)

# Calculate and print evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy on test set:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Training set size: (6134, 5000)
Test set size: (2629, 5000)
Accuracy on test set: 0.9303917839482693

Classification Report:
              precision    recall  f1-score   support

           0       0.93      1.00      0.96      2254
           1       0.99      0.52      0.68       375

    accuracy                           0.93      2629
   macro avg       0.96      0.76      0.82      2629
weighted avg       0.93      0.93      0.92      2629

Confusion Matrix:
[[2252    2]
 [ 181  194]]


In [28]:
# Model Training: Train a logistic regression model
logreg_clf = LogisticRegression(random_state=42, max_iter=1000)
logreg_clf.fit(X_train, y_train)

# Model Evaluation: Predict and evaluate on the test set
y_pred = logreg_clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy on test set:", accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy on test set: 0.9383796120197794

Classification Report:
              precision    recall  f1-score   support

           0       0.93      1.00      0.97      2254
           1       0.98      0.58      0.73       375

    accuracy                           0.94      2629
   macro avg       0.96      0.79      0.85      2629
weighted avg       0.94      0.94      0.93      2629

Confusion Matrix:
[[2250    4]
 [ 158  217]]


In [29]:
# Step 4: Model Training using MLP
# Configure the MLP with one hidden layer of 100 neurons, using ReLU activation and Adam optimizer
mlp_clf = MLPClassifier(hidden_layer_sizes=(100,), activation='relu', solver='adam', 
                        random_state=42, max_iter=300)

mlp_clf.fit(X_train, y_train)

# Step 5: Model Evaluation
y_pred = mlp_clf.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy on test set:", accuracy)

# Detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy on test set: 0.9627234689996196

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.99      0.98      2254
           1       0.91      0.82      0.86       375

    accuracy                           0.96      2629
   macro avg       0.94      0.90      0.92      2629
weighted avg       0.96      0.96      0.96      2629

Confusion Matrix:
[[2225   29]
 [  69  306]]
